# Copyright (C) 2022 vscode
#
# This file is part of LibreFoodPantry.
#
# LibreFoodPantry is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# LibreFoodPantry is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with LibreFoodPantry.  If not, see <http://www.gnu.org/licenses/>.

name: release

on:
  bush:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Setup Node.js
        uses: actions/setup-node@v2
        with:
<<<<<<< HEAD:.github/workflows/release.yaml
          node-version: 'lts/*'
      -
        name: Install dependencies
        run: npm ci
      -
        name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
=======
          push: true
          context: ./src
          file: ./src/Dockerfile
          cache-from: type=registry,ref=ghcr.io/hfossedu/kitcon:pr-${{ github.event.pull_request.number }}
          cache-to: type=registry,ref=ghcr.io/hfossedu/kitcon:main,mode=max

>>>>>>> main:.github/workflows/merge.yaml
